### ISSUE TITLE
Windows installer does not install 1.3

### ISSUE THREAD

**Issue by XerMat** [charwick/helipad#3]
Using pip install -U helipad in a Windows system installs an old version of helipad that is broken (the misnamed graphics.py file that does not have the complete code that is included in visualize.py that I installed on my Ubuntu machine.

**Comment by charwick** [comment]
Looks like Anaconda defaults to a `cp1252` encoding for `open()`, so the emoji in `README.md` are throwing it off, causing it to try to fall back to earlier versions until it finds one without the emoji. I've added an `encoding='utf-8'` argument to `open()` in `setup.py`, which should allow Anaconda to successfully install it. https://github.com/charwick/helipad/commit/9c3b33bd0cc283d9254856a561ccace2ef4c40db

I've just pushed a 1.3.1 update, which seems to install correctly on Anaconda now – clear your Pip cache and see if that works.

**Comment by XerMat** [comment]
Yes, that change worked.  Version 3.1 installed.  Now, if I can run the
samples...

I hold a masters degree in system dynamics from WPI, and am a well seasoned
user of Vensim, Stella, and NetLogo, so I am keen to test out the Helipad
framework.

Regards,
