### ISSUE TITLE
'NoneType' object has no attribute 'down' - PatchesRect.neighbors

### ISSUE THREAD

**Issue by tkristinwilson** [charwick/helipad#4]
Hi, I've started using the Helipad framework in anger recently - thank you for sharing it!

I'm currently trying to setup a non-wrapping grid with corners on, so I can call neighbors on a patch and get the Moore neighbourhood, but the combination of (wrap=False, corners=True) throws an error on setup - is this a supported combination?

### Details

helipad: v1.6.1
Error: AttributeError: 'NoneType' object has no attribute 'down' (on: patch.left.down)
Line: spatial.py:165 (in PatchesRect.neighbors)
if self.corners: neighbors += [(patch.down.right, self.corners), (patch.left.down, self.corners)]

### Code to Reproduce

import helipad
print(helipad.__version__)

from helipad import Helipad

heli = Helipad()
heli.name = 'Model Name'
heli.agents.order = 'random' 
heli.stages = 1

heli.param('stopafter', 'debug_run')

@heli.event
def debug_run(model):
    return model.t >= 20

mapPlot = heli.spatial(dim=(10,10), wrap=False, corners=False)   # 1. OK
mapPlot = heli.spatial(dim=(10,10), wrap=True, corners=True)     # 2. OK
mapPlot = heli.spatial(dim=(10,10), wrap=False, corners=True)    # 3. Not OK

heli.launchVisual()

**Comment by charwick** [comment]
Good catch, thanks; that should definitely work. I've pushed https://github.com/charwick/helipad/commit/962c56394f285573d6bd7ae8ba66689e5e5b1500 with a fix; I'll package that up and release 1.6.2 with it tomorrow.
